### ISSUE TITLE
Cannot start latest scenario editor

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#124]
I get the following message, and after `npm i` and `npm update` and `npm i -g mastarm`, it still remains:

```
Error: Cannot find module 'postcss-reporter'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/matthewc/conveyal/scenario-editor/node_modules/mastarm/lib/transform.js:77:7
    at makeTransform (/Users/matthewc/conveyal/scenario-editor/node_modules/module-deps/index.js:260:21)
    at /Users/matthewc/conveyal/scenario-editor/node_modules/module-deps/index.js:234:9
    at Deps.getTransforms (/Users/matthewc/conveyal/scenario-editor/node_modules/module-deps/index.js:239:7)
    at /Users/matthewc/conveyal/scenario-editor/node_modules/module-deps/index.js:379:24
    at onresolve (/Users/matthewc/conveyal/scenario-editor/node_modules/module-deps/index.js:191:14)
    at /Users/matthewc/conveyal/scenario-editor/node_modules/browserify/index.js:489:17
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by mattwigway** [comment]
`npm i postcss-reporter` gets it going as a stopgap.

**Comment by trevorgerhardt** [comment]
Fixed in the latest mastarm
